//Authentication
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_FAILED = "AUTH_FAILED";
export const FORGOT_PASS = "FORGOT_PASS";
export const FORGOT_PASS_FAILED = "FORGOT_PASS_FAILED";
export const RESET_PASS = "RESET_PASS";
export const RESET_PASS_FAILED = "RESET_PASS_FAILED";

// Independent Physical Asset
export const PHYSICAL_ASSETS_LOADING = "PHYSICAL_ASSETS_LOADING";
export const PHYSICAL_ASSETS_FAILED = "PHYSICAL_ASSETS_FAILED";
export const PHYSICAL_ASSETS_SUCCESS = "PHYSICAL_ASSETS_SUCCESS";
export const ADD_PHYSICAL_ASSET = "ADD_PHYSICAL_ASSET";
export const PHYSICAL_ASSETS_UPDATION = "PHYSICAL_ASSETS_UPDATION";
export const ILLEGAL_BID = "ILLEGAL_BID";
export const LEGAL_BID = "LEGAL_BID";
export const GET_ITEM = "GET_ITEM";
export const ITEM_LOADING = "ITEM_LOADING";
export const ITEM_FAILED = "ITEM_FAILED";

//GET PROFILE
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";
export const RESET_USER_PROFILE = "RESET_USER_PROFILE";

//CONTACT-US
export const CONTACT_US = "CONTACT_US";
export const FORM_FAILED = "FORM_FAILED";



export const POST_FAIL = "POST_FAIL";

//AUCTION LISTING
export const GET_AUCTION_LIST = "GET_AUCTION_LIST";
export const GET_FILTERED_AUCTION = "GET_FILTERED_AUCTION";
export const GET_AUCTION_LIST_ERROR = "GET_AUCTION_LIST_ERROR";
export const LOADING_AUCTION_LIST = "LOADING_AUCTION_LIST";

// AUCTION CREATION
export const CREATE_LIVE_AUCTION="CREATE_LIVE_AUCTION";
export const CREATE_LIVE_AUCTION_FAILED="CREATE_LIVE_AUCTION_FAILED";

